### ISSUE TITLE
Cannot install megatron-core[dev] - nv-grouped-gemm build error

### ISSUE THREAD

**Issue by sbhavani** [NVIDIA/Megatron-LM#2541]
**Describe the bug**

Installing megatron-core[dev] fails due to a build error in the nv-grouped-gemm dependency. The PyPI source distribution of nv-grouped-gemm is missing CUTLASS headers required for compilation, causing the installation to fail with a "cutlass/bfloat16.h: No such file or directory" error.

**Steps/Code to reproduce bug**

```
  # Attempt to install megatron-core with dev extras
  pip install "megatron-core[dev]>=0.15.0a0,<0.17.0"
```

Environment:
  - Python: 3.12.3
  - CUDA: 12.6 (system) / 12.8 (PyTorch)
  - PyTorch: 2.9.1+cu128
  - OS: Ubuntu 24.04
  - uv: 0.8.17

  Complete error output:
```
  Using CPython 3.12.3 interpreter at: /usr/bin/python3
  Resolved 131 packages in 46ms
     Building transformer-engine-torch==2.9.0
     Building nv-grouped-gemm==1.1.4.post6
    × Failed to build `nv-grouped-gemm==1.1.4.post6`
    ├─▶ The build backend returned an error
    ╰─▶ Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)

        [stdout]
        running bdist_wheel
        Guessing wheel URL:
        https://github.com/fanshiqing/grouped_gemm/releases/download/v1.1.4.post6/nv_grouped_gemm-1.1.4.post6+cu12torch2.9
  cxx11abiTRUE-cp312-cp312-linux_x86_64.whl
        Precompiled wheel not found. Building from source...
        running build
        running build_py
        running egg_info
        writing nv_grouped_gemm.egg-info/PKG-INFO
        writing dependency_links to nv_grouped_gemm.egg-info/dependency_links.txt
        writing requirements to nv_grouped_gemm.egg-info/requires.txt
        writing top-level names to nv_grouped_gemm.egg-info/top_level.txt
        reading manifest file 'nv_grouped_gemm.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        adding license file 'LICENSE'
        writing manifest file 'nv_grouped_gemm.egg-info/SOURCES.txt'
        running build_ext
        building 'grouped_gemm_backend' extension
        /usr/local/cuda/bin/nvcc
        -I/teamspace/studios/this_studio/.cache/uv/sdists-v9/pypi/nv-grouped-gemm/1.1.4.post6/fmIhCfoe3_aGrCQ2m7BtG/src/th
  ird_party/cutlass/include/

  -I/teamspace/studios/this_studio/.cache/uv/sdists-v9/pypi/nv-grouped-gemm/1.1.4.post6/fmIhCfoe3_aGrCQ2m7BtG/src/csrc
        -I/usr/local/cuda/include -I/usr/include/python3.12
        -c csrc/grouped_gemm.cu -o build/temp.linux-x86_64-cpython-312/csrc/grouped_gemm.o
        -std=c++17 -DENABLE_BF16 -DTORCH_API_INCLUDE_EXTENSION_H
        -DTORCH_EXTENSION_NAME=grouped_gemm_backend
        -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75
        -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86
        -gencode=arch=compute_90,code=sm_90

        [stderr]
        W1204 21:23:42.331000 19050 torch/utils/cpp_extension.py:630] Attempted
        to use ninja as the BuildExtension backend but we could not find ninja..
        Falling back to using the slow distutils backend.
        warning: no files found matching '*' under directory 'third_party'
        warning: manifest_maker: MANIFEST.in, line 4: unknown action 'README.md'

        W1204 21:23:42.353000 19050 torch/utils/cpp_extension.py:521] The
        detected CUDA version (12.6) has a minor version mismatch with the
        version that was used to compile PyTorch (12.8). Most likely this
        shouldn't be a problem.

        csrc/grouped_gemm.cu:8:10: fatal error: cutlass/bfloat16.h: No such file or directory
            8 | #include "cutlass/bfloat16.h"
              |          ^~~~~~~~~~~~~~~~~~~~
        compilation terminated.
        error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1

    help: `nv-grouped-gemm` (v1.1.4.post6) was included because
          `megatron-core[dev]` (v0.16.0rc0.dev132713) depends on `nv-grouped-gemm`
```

**Expected behavior**

Users should be able to set up a development environment with a single pip install command without encountering build failures.

**Additional context**

This blocks installation of downstream packages like `megatron-bridge` that depend on `megatron-core[dev]`

**Comment by ko3n1g** [comment]
I have pushed a fix to nv-grouped-gemm that should resolve this issue

**Comment by phtu-cs** [comment]
> I have pushed a fix to nv-grouped-gemm that should resolve this issue

Still see the same issue when running `uv run` in megatron-bridge.

**Comment by ko3n1g** [comment]
Thank you for sharing. It looks like this is more related to how megatron-bridge manages its dependencies rather than to MLM or grouped-gemm. As long as you can confirm that with MLM you dont see this issue another, I would recommend to move the discussion to MBridge.

**Comment by sbhavani** [comment]
This has been resolved by #3770, which removed the unused `nv-grouped-gemm` dependency from Megatron-LM’s `dev` and `lts` extras. Closing as completed.

If this still occurs in Megatron Bridge, please open or continue an issue there with the resolved Megatron-LM version, since older pinned releases may still include the dependency.
